const people = [
  {
    id: "1",
    name: "Rafael",
    pos: "Torcedor",
    city: "sp",
    state: "SP",
    phone: "11111111",
    description: "Eu",
  },
  {
    id: "2",
    name: "Weverton",
    pos: "G",
    city: "sp",
    state: "SP",
    phone: "222222222",
    description: "Paredão",
  },
  {
    id: "3",
    name: "Marcos Rocha",
    pos: "LD",
    city: "sp",
    state: "SP",
    phone: "3333333",
    description: "Melhor q fagner",
  },
  {
    id: "4",
    name: "Piquerez",
    pos: "LE",
    city: "sp",
    state: "SP",
    phone: "11111111",
    description: "CAMPEON PELO PARMERAAA",
  },
  {
    id: "5",
    name: "Gustavo Gomez",
    pos: "ZG",
    city: "sp",
    state: "SP",
    phone: "11111111",
    description: "Capita",
  },
  {
    id: "6",
    name: "Murilo",
    pos: "ZG",
    city: "sp",
    state: "SP",
    phone: "33333333",
    description:
      "Melhor contratação de 2022, mas tomou vermelho na semifinal da liberta mt triste",
  },
  {
    id: "7",
    name: "Zé Rafael",
    pos: "VOL",
    city: "sp",
    state: "SP",
    phone: "2222",
    description: "TREM",
  },
  {
    id: "8",
    name: "Danilo",
    pos: "VOL",
    city: "sp",
    state: "SP",
    phone: "11111111",
    description: "Melhor amigo do presidente da conmebol",
  },
  {
    id: "9",
    name: "Raphael Veiga",
    pos: "ME",
    city: "sp",
    state: "SP",
    phone: "111333311111",
    description: "Orgulho do vô",
  },
  {
    id: "10",
    name: "Gustavo Scarpa",
    pos: "ME",
    city: "sp",
    state: "SP",
    phone: "333333",
    description: "Skatista indo pro ultimo lugar da premiere",
  },
  {
    id: "11",
    name: "Dudu",
    pos: "AT",
    city: "sp",
    state: "SP",
    phone: "222222",
    description: "BAIXOLA",
  },
  {
    id: "12",
    name: "Rony",
    pos: "AT",
    city: "sp",
    state: "SP",
    phone: "11111111",
    description: "Melhor q cr7",
  },
  {
    id: "13",
    name: "Mayke",
    pos: "LD",
    city: "sp",
    state: "SP",
    phone: "33333",
    description: "É lateral ou ponta?",
  },
  {
    id: "14",
    name: "Endrick",
    pos: "AT",
    city: "sp",
    state: "SP",
    phone: "11111111",
    description: "Melhor q pelé",
  },
  {
    id: "15",
    name: "Luan",
    pos: "ZG",
    city: "sp",
    state: "SP",
    phone: "33333333",
    description: "Um zagueiro mt bom, mas azarado",
  },
  {
    id: "bagre",
    name: "Jorge",
    pos: "Era pra ser LE",
    city: "sp",
    state: "SP",
    phone: "11111111",
    description: "Bagre, q q esse cara tá fazendo aqui ainda?...",
  },
  {
    id: "16",
    name: "Flaco Lopes",
    pos: "AT",
    city: "sp",
    state: "SP",
    phone: "2222222",
    description: "-",
  },
  {
    id: "17",
    name: "Abel Ferreira",
    pos: "Tec",
    city: "sp",
    state: "SP",
    phone: "333333",
    description: "Abel pra presidente, já",
  },
  {
    id: "18",
    name: "Vanderlan",
    pos: "LE",
    city: "sp",
    state: "SP",
    phone: "333333",
    description: "Deixa o jorge no chinelo",
  },
];

export { people };
